name: "Bump version when merging Pull Requests with specific labels"

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - packages/components/**
      - .github/workflows/components-bump-version.yml

jobs:
  bump_version:
    name: "Pull Request Merged"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Build
        run: npm run build
      - name: Set git config
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Major version bump
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: cd packages/components && npm --tag-version-prefix="test-v" version major -m 'Release major version %s' && git push && git push --tags
      - name: Minor version bump
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: cd packages/components && npm --tag-version-prefix="test-v" version minor -m 'Release minor version %s' && git push && git push --tags
      - name: Patch version bump
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: cd packages/components && npm --tag-version-prefix="test-v" version patch -m 'Release patch version %s' && git push && git push --tags
