name: Run only when merging PRs with label named "minor" or "major"

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge_pr:
    name: "PR Merged"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
      - name: Set git config
        run: |
          git config --global user.name 'MapsPeople A/S'
          git config --global user.email 'mail@mapspeople.com'
      - name: Build
        run: npm run build
      - name: Apply version bump (major)
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: npm --no-git-tag-version version major -m "Release new major version %s"
      - name: Apply version bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: npm --no-git-tag-version version minor -m "Release new minor version %s"
      - name: Apply version bump (patch)
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: npm --no-git-tag-version version patch -m "Release new patch version %s"
      - name: Git push version bump
        run: git push origin main --force
      - name: Output version change
        run: npm pkg get version
